service: feedback-survey

plugins:
  - serverless-domain-manager

custom:
  surveyTableName: 'feedback_survey-${self:provider.stage}'
  questionTableName: 'feedback_question-${self:provider.stage}'
  answerTypeTableName: 'feedback_answer-type-${self:provider.stage}'
  emailTableName: 'feedback_email-${self:provider.stage}'

  customDomain:
    domainName: ${opt:domain}
    basePath: 'api'
    stage: ${self:provider.stage}
    createRoute53Record: true

provider:
  name: aws
  runtime: java8
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["surveyTable", "Arn"] }
        - { "Fn::GetAtt": ["questionTable", "Arn"] }
        - { "Fn::GetAtt": ["answerTypeTable", "Arn"] }
        - { "Fn::GetAtt": ["emailTable", "Arn"] }

    - Effect: "Allow"
      Action:
        - "ses:SendEmail"
        - "ses:SendRawEmail"
      Resource: "*"

  environment:
    SURVEY_TABLE_NAME: ${self:custom.surveyTableName}
    QUESTION_TABLE_NAME: ${self:custom.questionTableName}
    ANSWER_TYPE_TABLE_NAME: ${self:custom.answerTypeTableName}
    EMAIL_TABLE_NAME: ${self:custom.emailTableName}


package:
  artifact: target/feedback-survey-1.jar

functions:
  saveSurvey:
    handler: com.buildit.survey.SaveSurveyHandler
    timeout: 30
    events:
      - http:
          path: /saveSurvey
          method: post
          cors: true

  getQuestions:
    handler: com.buildit.question.GetQuestionsHandler
    events:
      - http:
          path: /getQuestions
          method: get
          cors: true

  saveQuestions:
    handler: com.buildit.question.SaveQuestionsHandler
    events:
      - http:
          path: /saveQuestions
          method: post
          authorizer: aws_iam

  saveAnswerTypes:
    handler: com.buildit.question.SaveAnswerTypesHandler
    events:
      - http:
          path: /saveAnswerTypes
          method: post
          authorizer: aws_iam

  saveEmail:
    handler: com.buildit.email.SaveEmailHandler
    events:
      - http:
          path: /saveEmail
          method: post
          authorizer: aws_iam

resources:
  Resources:
    surveyTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.surveyTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    questionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.questionTableName}
        AttributeDefinitions:
          - AttributeName: name
            AttributeType: S
          - AttributeName: ordinal
            AttributeType: N
        KeySchema:
          - AttributeName: name
            KeyType: HASH
          - AttributeName: ordinal
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    answerTypeTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.answerTypeTableName}
        AttributeDefinitions:
          - AttributeName: type
            AttributeType: S
        KeySchema:
          - AttributeName: type
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1

    emailTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ${self:custom.emailTableName}
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: N
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
