package com.buildit.survey;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.util.List;

@DynamoDBTable(tableName = "PLACEHOLDER_SURVEY_TABLE_NAME")
public class Survey {

    static final String SURVEY_TABLE_NAME = System.getenv("SURVEY_TABLE_NAME");

    private String id;

    private String clientName;

    private List<String> answers;

    @DynamoDBHashKey(attributeName = "id")
    @DynamoDBAutoGeneratedKey
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getClientName() {
        return clientName;
    }

    public void setClientName(String clientName) {
        this.clientName = clientName;
    }

    public List<String> getAnswers() {
        return answers;
    }

    public void setAnswers(List<String> answers) {
        this.answers = answers;
    }

    @Override
    public String toString() {
        return "Survey{" +
                "id=" + id +
                ", clientName='" + clientName + '\'' +
                ", answers=" + answers +
                '}';
    }
}
